# Generated by Django 2.1.2 on 2018-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerypage_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='轮播图简介'),
        ),
    ]
