# Generated by Django 2.1.3 on 2018-12-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20181205_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='intro',
            new_name='glinks',
        ),
    ]
