# Generated by Django 2.1.3 on 2018-12-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20181205_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='glinks',
            new_name='intro',
        ),
    ]
